---
title: "p8105_hw6_ts3349"
author: "Tessa Senders"
date: "12/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r import libraries}
library(tidyverse)
library(broom)
library(p8105.datasets)
library(purrr)
library(modelr)
```


## Problem 1






## Problem 2


```{r load and tidy data}
birthweight_df <- read_csv("./data/birthweight.csv") %>%
  janitor::clean_names() %>%
  mutate(babysex = as_factor(babysex),
         frace = as_factor(frace),
         malform = as_factor(malform),
         mrace = as_factor(mrace))

birthweight_df %>% 
  map(~sum(is.na(.)))
```

```{r prob 2, 2 given models}
set.seed(1)
fit_1 = lm(bwt ~ blength + gaweeks, data = birthweight_df)
fit_2 = lm(bwt ~ bhead * blength * babysex, data = birthweight_df)

cv_df =
  crossv_mc(birthweight_df, 100) %>% 
  mutate(
    train = map(train, as_tibble),
    test = map(test, as_tibble))

cv_df = 
  cv_df %>% 
  mutate(
    simple_model = map(train, ~lm(bwt ~ blength + gaweeks, data = .x)),
    interaction_model = map(train, ~lm(bwt ~ bhead * blength * babysex, data = .x))
    #my_model = map() 
  ) %>%
    
  mutate(
    rmse_simple = map2_dbl(simple_model, test, ~rmse(model = .x, data = .y)),
    rmse_interaction = map2_dbl(interaction_model, test, ~rmse(model = .x, data = .y)),
    rmse_smooth = map2_dbl(smooth_mod, test, ~rmse(model = .x, data = .y))
    )






#fit_1 %>% 
#  broom::glance()
#fit_1 %>%
#  broom::tidy()

#fit_2 %>%
#  broom::glance()
#fit_2 %>%
#  broom::tidy()

```


One using length at birth and gestational age as predictors (main effects only)
One using head circumference, length, sex, and all interactions (including the three-way interaction) between these
Make this comparison in terms of the cross-validated prediction error; use crossv_mc and functions in purrr as appropriate

## Problem 3


```{r prob 3 load data}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r prob 3 draw samples}
set.seed(1)

boot_sample = function(df) {
  sample_frac(df, replace = TRUE)
}

boot_straps = 
  data_frame(
    strap_number = 1:5000,
    strap_sample = rerun(5000, boot_sample(weather_df))
  )


bootstrap_results = 
  boot_straps %>% 
  mutate(
    models = map(strap_sample, ~lm(tmax ~ tmin, data = .x)),
    results = map(models, broom::glance),  
    results_2 = map(models, broom::tidy)) %>%
  select(-strap_sample, -models) %>% 
  unnest(results,
         results_2) %>% 
  select(strap_number, r.squared, term, estimate) %>%
  pivot_wider(names_from = term,
              values_from = estimate) %>%
  janitor::clean_names() %>%
  mutate(log_value = log(intercept * tmin))

bootstrap_results
```


```{r prob 3 plots}
bootstrap_results %>% 
  ggplot(aes(x = tmin)) + 
  geom_density() + 
  labs(
    title = "5000 Boostrap Estimates of Minimum Temperature (C)",
    x = "Minimum Temperature (C)",
    y = "Density",
    caption = "Data from the New York NOAA weather stations"
  )

bootstrap_results %>%
  ggplot(aes(x = log_value)) + 
  geom_density()+ 
  labs(
    title = "5000 Boostrap Estimates of log(B_0_hat * B_1_hat)",
    x = "log(B_0_hat * B_1_hat)",
    y = "Density",
    caption = "Data from the New York NOAA weather stations"
  )
```


```{r problem 3 quantiles}
bootstrap_results %>% 
  summarize(
    ci_lower_tmin = quantile(tmin, 0.025), 
    ci_upper_tmin = quantile(tmin, 0.975),
    ci_lower_log = quantile(log_value, 0.025), 
    ci_upper_log = quantile(log_value, 0.975))
```

